version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  name: Nuget_Release
  api_key:
    secure: 7M1+hgMfmA3p/WVC/vOqPLRDZObbU+A6D3SbPzkkD/W/9N7OmwNMEhxve7iwHQVk
  skip_symbols: false
  artifact: /.*\.nupkg/
