version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: l48GJ3P7lYSqWbJrGF/t4JejKsBUpNw8O9VMmyg4A4a0eOm8BrvHj7JzLWV5BEVh
  skip_symbols: false
  artifact: /.*\.nupkg/
