version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
artifacts:
- path: /.*\.nupkg/
  name: Nuget
deploy:
- provider: NuGet
  name: nuget_release
  api_key:
    secure: 7M1+hgMfmA3p/WVC/vOqPLRDZObbU+A6D3SbPzkkD/W/9N7OmwNMEhxve7iwHQVk
  artifact: Nuget
  on:
    branch: master  
